### ISSUE TITLE
Can’t build centreon-connectors

### ISSUE THREAD

**Issue by M4rotte** [centreon/centreon-connectors#6]
Hi,

I have the following error when I try to build the Centreon SSH connector (branch master or 1.0) on CentOS 7:

`Building CXX object CMakeFiles/centreonconnectorssh.dir/usr/local/src/centreon-connectors/ssh/src/orders/parser.cc.o
/usr/local/src/centreon-connectors/ssh/src/options.cc: In member function 'void com::centreon::connector::ssh::options::_init()':
/usr/local/src/centreon-connectors/ssh/src/options.cc:155:27: error: no matching function for call to 'com::centreon::misc::argument::set_has_value(bool)'
     arg.set_has_value(true);
                           ^
/usr/local/src/centreon-connectors/ssh/src/options.cc:155:27: note: candidate is:
In file included from /centreon/include/com/centreon/misc/get_options.hh:26:0,
                 from /usr/local/src/centreon-connectors/ssh/build/../inc/com/centreon/connector/ssh/options.hh:23,
                 from /usr/local/src/centreon-connectors/ssh/src/options.cc:21:
/centreon/include/com/centreon/misc/argument.hh:62:24: note: void com::centreon::misc::argument::set_has_value(com::centreon::misc::argument::value_number)
     void               set_has_value(value_number val) throw ();
                        ^
/centreon/include/com/centreon/misc/argument.hh:62:24: note:   no known conversion for argument 1 from 'bool' to 'com::centreon::misc::argument::value_number'
make[2]: *** [CMakeFiles/centreonconnectorssh.dir/usr/local/src/centreon-connectors/ssh/src/options.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/centreonconnectorssh.dir/all] Error 2
make: *** [all] Error 2`

Centreon CLib has been built from the master branch, centreon-engine & centreon-broker both build and run OK.

What am I doing wrong?

**Comment by bouda1** [comment]
The CLib's master branch is not stable and not api compatible with centreon-connectors.

Rebuild clib from branch 1.4
It should be better. You probably will have to build also again centreon-engine.

**Comment by M4rotte** [comment]
Thx for your answer. I have not tested the software yet but the build was OK (both SSH & Perl). For each component I took the branch with the biggest version number. Which gives:
CLib : 1.4
Engine : 2.0
Broker : 2.12
Connectors : 1.0
Centreon : 2.8.x

Does it seems a good choice to you? Should I prefer "master" for some components? Is there any branches that can be interesting to test and that I should be aware of?
